name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # change to your .NET version
    - name: Build with dotnet
      run: dotnet build YourSolution.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test YourSolution.sln --configuration Release --no-build

